### ISSUE TITLE
URL links not working on the documentation page

### ISSUE THREAD

**Issue by christx2** [nuagenetworks/nuage-openstack-neutron#2]
Links dead on this page to Docs, Bugs, Source:

https://github.com/nuagenetworks/nuage-openstack-neutron/blob/master/README.rst

**Comment by phantium** [comment]
Can someone please update this? I also need the documentation.

**Comment by dttocs** [comment]
@phantium unfortunately the documentation is not published on github at this point, but you can obtain it from https://support.alcatel-lucent.com/portal/web/support if you have an account or your Nokia customer team until then.
